name: sxsw
favicon: null
layout_spectrum: 1
typography_spectrum: 0.30845
title: South By Southwest
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#343d46'
    - '#f86908'
    - '#95d703'
    - '#07aed3'
  brandStrength: 0.1875
  lightness: 0.1875
  saturation: 0.1875
  rhythmicContrast: 1
purpose: []
