name: sxsw
favicon: null
layout_spectrum: 0
typography_spectrum: 0
title: South By Southwest
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1a1825'
    - '#b4b9fb'
    - '#7971c6'
    - '#6d5c55'
    - '#ac7850'
  brandStrength: 0.75
  lightness: 0.8385900296270847
  saturation: 0.5231445950921625
  rhythmicContrast: 0.4307761916425079
purpose: []
