name: sxsw
favicon: null
layout_spectrum: 0.73752
typography_spectrum: 0.48389
title: South By Southwest
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#343d46'
    - '#f86908'
    - '#95d703'
    - '#07aed3'
  brandStrength: 0.8125
  lightness: 0.5
  saturation: 0.5231445950921625
  rhythmicContrast: 0.4307761916425079
purpose: []
